Notebook for learning Pandas

In [49]:
import pandas as pd
import numpy as np

In [8]:
# Series
ser1 = pd.Series([4, -3, -6, 6, 7])
print(ser1)
print(ser1.array)
print(ser1.index)

# You can assign the index
ser2 = pd.Series([2, 6, -7, 3], index=['d', 'b', 'c', 'a'])
print(ser2)
print(ser2.index)

# Calling a data point
print(ser2['a'])
print(ser2['d'])
print('a' in ser2)

ser2['c'] = 4
print(ser2['c'])

0    4
1   -3
2   -6
3    6
4    7
dtype: int64
<NumpyExtensionArray>
[4, -3, -6, 6, 7]
Length: 5, dtype: int64
RangeIndex(start=0, stop=5, step=1)
d    2
b    6
c   -7
a    3
dtype: int64
Index(['d', 'b', 'c', 'a'], dtype='object')
3
2
True
4

In [16]:
# Creating a series from a dict
data = {'Baguio': 126357, 'Bulacan': 7863826, 'Pampanga': 347628176, 'Manila': 7182318}

data_ser = pd.Series(data)
print(data_ser)

# Convert back
data_dict = data_ser.to_dict()
print(data_dict)

# Enforcing keys as indices. Indices with no values are assigned NaN, indices not included are dropped
cities = ['Pampanga', 'Baguio', 'Bulacan', 'Pasig']
data_ser2 = pd.Series(data, index=cities)
print(data_ser2)

pd.isna(data_ser2)
pd.notna(data_ser2)

# Setting names of Series and indices
data_ser2.name = 'population'
data_ser2.index.name = 'cities'

print(data_ser2)
print(data_ser2.index)

Baguio         126357
Bulacan       7863826
Pampanga    347628176
Manila        7182318
dtype: int64
{'Baguio': 126357, 'Bulacan': 7863826, 'Pampanga': 347628176, 'Manila': 7182318}
Pampanga    347628176.0
Baguio         126357.0
Bulacan       7863826.0
Pasig               NaN
dtype: float64
cities
Pampanga    347628176.0
Baguio         126357.0
Bulacan       7863826.0
Pasig               NaN
Name: population, dtype: float64
Index(['Pampanga', 'Baguio', 'Bulacan', 'Pasig'], dtype='object', name='cities')

In [30]:
# DataFrame
data ={
    'city': ['Baguio', 'Bulacan', 'Pampanga', 'Baguio', 'Bulacan', 'Pampanga'],
    'year': ['2000', '2000', '2000', '2001', '2001', '2001'],
    'pop': [1.2, 1.4, 1.6, 2.3, 2.7, 2.4]
}

frame = pd.DataFrame(data)
print(frame)
print(frame.head())

# Rearranging the columns, columns not in the dict will have NaN values
frame2 = pd.DataFrame(data, columns=['year', 'city', 'pop', 'debt'])
print(frame2)

# Columns can be modified by assignment
frame2['debt'] = np.arange(100_000, 700_000, 100_000)
frame2['gdp'] = 100_000_000
print(frame2)

       city  year  pop
0    Baguio  2000  1.2
1   Bulacan  2000  1.4
2  Pampanga  2000  1.6
3    Baguio  2001  2.3
4   Bulacan  2001  2.7
5  Pampanga  2001  2.4
       city  year  pop
0    Baguio  2000  1.2
1   Bulacan  2000  1.4
2  Pampanga  2000  1.6
3    Baguio  2001  2.3
4   Bulacan  2001  2.7
   year      city  pop debt
0  2000    Baguio  1.2  NaN
1  2000   Bulacan  1.4  NaN
2  2000  Pampanga  1.6  NaN
3  2001    Baguio  2.3  NaN
4  2001   Bulacan  2.7  NaN
5  2001  Pampanga  2.4  NaN
   year      city  pop    debt        gdp
0  2000    Baguio  1.2  100000  100000000
1  2000   Bulacan  1.4  200000  100000000
2  2000  Pampanga  1.6  300000  100000000
3  2001    Baguio  2.3  400000  100000000
4  2001   Bulacan  2.7  500000  100000000
5  2001  Pampanga  2.4  600000  100000000

In [36]:
# In nested dicts, inner keys are interpreted as indices and outer keys as columns
populations = {
    'Baguio': {2000: 1.3, 2001: 1.6, 2002: 3.5},
    'Bulacan': {2000: 1.6, 2001: 1.9, 2002: 2.5},
    'Pampanga': {2000: 1.8, 2001: 1.0, 2002: 4.5, 2004: 5.2}
}

frame3 = pd.DataFrame(populations)
print(frame3)

# Transposing is similar to numpy
# Note that transposing may discard column data types which are lost when you transpose it back
frame4 = frame3.T 
print(frame4)

      Baguio  Bulacan  Pampanga
2000     1.3      1.6       1.8
2001     1.6      1.9       1.0
2002     3.5      2.5       4.5
2004     NaN      NaN       5.2
          2000  2001  2002  2004
Baguio     1.3   1.6   3.5   NaN
Bulacan    1.6   1.9   2.5   NaN
Pampanga   1.8   1.0   4.5   5.2

In [40]:
# Index objects
# Rows and columns are treated as index objects, which are objects responsible for holding axis labels and metadata
# Index objects behave as set objects
frame3.index.name = 'year'
frame3.columns.name = 'cities'

print(frame3.columns)
print(frame3.index)

print('Baguio' in frame3.columns)

Index(['Baguio', 'Bulacan', 'Pampanga'], dtype='object', name='cities')
Index([2000, 2001, 2002, 2004], dtype='int64', name='year')
True

In [ ]:
# Reindexing aligns the indices
# This is especially valuable for time-series gaps, dataset alignment, controlled report layouts, and making missing data explicit.
# For example: adding missing dates
dates = pd.date_range("2026-01-01", "2026-01-05")

df = df.set_index("date").reindex(dates)

# Put rows in specific order
df = df.reindex(["critical", "high", "medium", "low"])

# Align two datasets before calculations
revenue = revenue.reindex(customers)
costs = costs.reindex(customers)

profit = revenue - costs

In [48]:
# Fill missing data
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0,2,4])

print(obj3)

obj3.reindex(np.arange(6), method='ffill')

0      blue
2    purple
4    yellow
dtype: object

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [ ]:
# Dropping entries in a series
obj = pd.Series(np.arange(5), index=['a', 'b', 'c', 'd', 'e'])
obj

new_obj = obj.drop('c')
new_obj

a    0
b    1
d    3
e    4
dtype: int64

In [86]:
# Dropping entries from a DataFrame
obj_df = pd.DataFrame(
    np.arange(16).reshape((4,4)),
    index=['Baguio', 'Bulacan', 'Manila', 'Pampanga'],
    columns=['one', 'two', 'three', 'four']
)

new_df = obj_df.drop(index=['Manila'])
new_df = new_df.drop(columns=['two'])

print(obj_df)
print(new_df)

          one  two  three  four
Baguio      0    1      2     3
Bulacan     4    5      6     7
Manila      8    9     10    11
Pampanga   12   13     14    15
          one  three  four
Baguio      0      2     3
Bulacan     4      6     7
Pampanga   12     14    15

In [63]:
# Indexing
obj[['b', 'a', 'd']]
obj['d']

np.int64(3)

In [ ]:
# Indexing using the loc operator - this is the preferred method
# loc is label-based
obj.loc[['b', 'a', 'd']]

b    1
a    0
d    3
dtype: int64

In [66]:
# You can also slice using the loc operator but the range is inclusive
obj.loc['b':'d']

b    1
c    2
d    3
dtype: int64

In [ ]:
# iloc is integer or physical position based
obj.iloc[[1,2,0]]

b    1
c    2
a    0
dtype: int64

In [ ]:
# Slicing using iloc is similar to normal Py slicing, where the endpoint is exclusive
obj.iloc[1:3]

b    1
c    2
dtype: int64

In [70]:
# Indexing into a DataFrame retrieves one or more columns
obj_df[['two', 'four']]

          two  four
Baguio      1     3
Bulacan     5     7
Manila      9    11
Pampanga   13    15

In [72]:
# Indexing using ranges selects rows
obj_df[1:3]

         one  two  three  four
Bulacan    4    5      6     7
Manila     8    9     10    11

In [74]:
# You can also index with a boolean array
obj_df[obj_df['two'] > 5]

          one  two  three  four
Manila      8    9     10    11
Pampanga   12   13     14    15

In [78]:
# The above method can also be used to assign values
obj_df[obj_df < 5] = 0
obj_df[obj_df > 5] = 1
obj_df

          one  two  three  four
Baguio      0    0      0     0
Bulacan     0    5      1     1
Manila      1    1      1     1
Pampanga    1    1      1     1

In [80]:
# Selection on DataFrame using loc and iloc
obj_df.loc['Baguio']

one      0
two      1
three    2
four     3
Name: Baguio, dtype: int64

In [83]:
obj_df.loc[['Baguio', 'Bulacan']]

         one  two  three  four
Baguio     0    1      2     3
Bulacan    4    5      6     7

In [84]:
# Combining row and column selection
obj_df.loc[['Baguio', 'Bulacan'], ['two', 'three']]

         two  three
Baguio     1      2
Bulacan    5      6

In [87]:
# Using slices with loc
obj_df.loc[:'Manila', 'three']

Baguio      2
Bulacan     6
Manila     10
Name: three, dtype: int64

In [91]:
# Selection using iloc
obj_df.iloc[2]

one       8
two       9
three    10
four     11
Name: Manila, dtype: int64

In [94]:
obj_df.iloc[:3, 2]

Baguio      2
Bulacan     6
Manila     10
Name: three, dtype: int64

In [108]:
# Arithmetic operations
df1 = pd.DataFrame(
    np.arange(12).reshape((3,4)),
    columns=list('abcd')
    )

df2 = pd.DataFrame(
    np.arange(20).reshape((4,5)),
    columns=list('abcde')
    )

# Placing a NaN inside
df2.loc[1, 'b'] = np.nan

print(df1)
print(df2)

   a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11
    a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19

In [104]:
# Adding DFs will results to a union of the DFs with NaN as values for non-overlapping elements
total = df1 + df2
print(total)

# You can use the fill_value argument of add method to fill in missing values
total1 = df1.add(df2, fill_value=0)
print(total1)

# You can also try to reindex one table first before peforming the operation to align the location of the elements
reindexed_df1 = df1.reindex(columns=df2.columns, index=df2.index, fill_value=0)
print(reindexed_df1)

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN
      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0
   a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0
3  0  0   0   0  0

In [ ]:
# Operations between DFs and series
ser1 = np.arange(4)

# The series elements are subtracted once for each row, this is referred to as broadcasting
diff = df1 - ser1
print(diff)

   a  b  c  d
0  0  0  0  0
1  4  4  4  4
2  8  8  8  8

In [113]:
# Broadcasting over the columns, matching on the rows, will need to specify the index
df3 = df1.reindex(index=df2.index, fill_value=0)

diff2 = df3.sub(ser1, axis='index')
print(diff2)

   a  b  c  d
0  0  1  2  3
1  3  4  5  6
2  6  7  8  9
3 -3 -3 -3 -3

In [134]:
# Function application and mapping
frame = pd.DataFrame(
    np.random.standard_normal((4,3)),
    columns=list('bed'),
    index=['Baguio', 'Bulacan', 'Pampanga', 'Manila']
)

print(frame)

# NP ufuncs also work with pandas objects
frame2 = np.abs(frame)
print(frame2)

                 b         e         d
Baguio    0.100559 -0.649541 -0.481974
Bulacan   1.583229 -0.821625 -0.571045
Pampanga -0.776748 -0.600111 -0.556000
Manila    1.591120  0.324946 -0.727054
                 b         e         d
Baguio    0.100559  0.649541  0.481974
Bulacan   1.583229  0.821625  0.571045
Pampanga  0.776748  0.600111  0.556000
Manila    1.591120  0.324946  0.727054

In [ ]:
# Functions on 1D arrays can also be applied to rows or columns using DF apply method
# Functions for axis-wise execution, use apply
def func(x):
    return x.max() - x.min()

frame.apply(func)

b    2.081423
d    2.895849
e    2.301252
dtype: float64

In [120]:
# To apply func across columns, use axis argument
frame.apply(func, axis='columns')

Baguio      2.692447
Bulacan     2.504655
Pampanga    1.166577
Manila      1.551486
dtype: float64

In [ ]:
# Functions applied through apply can also return a series with multiple values
def func2(x):
    return pd.Series([x.min(), x.max(), func(x)], index=['min', 'max', 'diff'])

frame.apply(func2)

             b         d         e
min  -1.518430 -0.977229 -0.586035
max   0.562993  1.918620  1.715218
diff  2.081423  2.895849  2.301252

In [125]:
# Stat functions like sum and mean are DF methods and can be pulled without using apply
print(frame.sum())
print(frame.mean())

b   -2.449511
d   -0.416934
e    1.032741
dtype: float64
b   -0.612378
d   -0.104233
e    0.258185
dtype: float64

In [ ]:
# Functions for element-wise execution, use applymap
def format(x):
    return f'{x:.2f}'

frame.applymap(format)

# Modern implementation use map method, which yields the same output
frame.map(format)

              b      d      e
Baguio     0.56  -0.98   1.72
Bulacan   -0.20   1.92  -0.59
Pampanga  -1.52  -0.56  -0.35
Manila    -1.30  -0.80   0.26

In [135]:
# To sort by row or column, use the sort_index(axis=) method which returns a new object
index_sorted = frame.sort_index()
index_sorted

                 b         e         d
Baguio    0.100559 -0.649541 -0.481974
Bulacan   1.583229 -0.821625 -0.571045
Manila    1.591120  0.324946 -0.727054
Pampanga -0.776748 -0.600111 -0.556000

In [137]:
column_sorted = frame.sort_index(axis='columns', ascending=False)
column_sorted

                 e         d         b
Baguio   -0.649541 -0.481974  0.100559
Bulacan  -0.821625 -0.571045  1.583229
Pampanga -0.600111 -0.556000 -0.776748
Manila    0.324946 -0.727054  1.591120

In [143]:
# To sort by values, use the sort_values method instead
reindex_frame = frame.reindex(index=['Baguio', 'Bulacan', 'Pampanga', 'Manila', 'Baler'])
print(reindex_frame)

sorted_reindex_frame = reindex_frame.sort_values('b')
print(sorted_reindex_frame)

sorted_reindex_frame = reindex_frame.sort_values(['b', 'd'], na_position='first')
print(sorted_reindex_frame)

                 b         e         d
Baguio    0.100559 -0.649541 -0.481974
Bulacan   1.583229 -0.821625 -0.571045
Pampanga -0.776748 -0.600111 -0.556000
Manila    1.591120  0.324946 -0.727054
Baler          NaN       NaN       NaN
                 b         e         d
Pampanga -0.776748 -0.600111 -0.556000
Baguio    0.100559 -0.649541 -0.481974
Bulacan   1.583229 -0.821625 -0.571045
Manila    1.591120  0.324946 -0.727054
Baler          NaN       NaN       NaN
                 b         e         d
Baler          NaN       NaN       NaN
Pampanga -0.776748 -0.600111 -0.556000
Baguio    0.100559 -0.649541 -0.481974
Bulacan   1.583229 -0.821625 -0.571045
Manila    1.591120  0.324946 -0.727054

In [ ]:
# Ranking assigns rank and breaks ties by assigning the mean rank
ser1 = pd.Series([5, 3, 0, 2, 4, 4, -8, -7, 6])

ser1.rank()

0    8.0
1    5.0
2    3.0
3    4.0
4    6.5
5    6.5
6    1.0
7    2.0
8    9.0
dtype: float64

In [148]:
print(ser1.sort_values())
ser1.sort_values().rank(ascending=False)

6   -8
7   -7
2    0
3    2
1    3
4    4
5    4
0    5
8    6
dtype: int64

6    9.0
7    8.0
2    7.0
3    6.0
1    5.0
4    3.5
5    3.5
0    2.0
8    1.0
dtype: float64

In [151]:
# DFs can compute ranks over either rows or columns
print(frame.rank(axis='columns'))
print(frame.rank(axis='index'))

            b    e    d
Baguio    3.0  1.0  2.0
Bulacan   3.0  1.0  2.0
Pampanga  1.0  2.0  3.0
Manila    3.0  2.0  1.0
            b    e    d
Baguio    2.0  2.0  4.0
Bulacan   3.0  1.0  2.0
Pampanga  1.0  3.0  3.0
Manila    4.0  4.0  1.0

In [ ]:
# Axis indexes with duplicate labels
obj = pd.Series(np.arange(5), index=['a', 'a', 'b', 'b', 'c'])

# CHecking if indices are unique
obj.index.is_unique

# Data selection with duplicate labels returns a Series, same with DFs
obj['a']

a    0
a    1
dtype: int64

In [157]:
# Descriptive stats
df = pd.DataFrame(
    [[1.4, np.nan], [7.1, -4.5],
     [np.nan, np.nan], [0.75, -1.31]],
     index=list('abcd'),
     columns=['one', 'two']
)
df

    one   two
a  1.40   NaN
b  7.10 -4.50
c   NaN   NaN
d  0.75 -1.31

In [161]:
# Built in methods can handle NaN values
print(df.sum())
print(df.sum(axis='columns'))
print(df.sum(axis='columns', skipna=False))

one    9.25
two   -5.81
dtype: float64
a    1.40
b    2.60
c    0.00
d   -0.56
dtype: float64
a     NaN
b    2.60
c     NaN
d   -0.56
dtype: float64

In [162]:
# Some aggs like mean require at least one non-NA value
df.mean(axis='columns')

a    1.40
b    1.30
c     NaN
d   -0.28
dtype: float64

In [168]:
# Some methods return indirect statistics like the index value
print(df.idxmax())

# Others are accumulations
print(df.cumsum())

# You can use describe method to produce summary statistics in one shot
print(df.describe())

# You can also use describe for non-numeric data
obj = pd.Series(list('abcd')*4)
obj.describe()

one    b
two    d
dtype: object
    one   two
a  1.40   NaN
b  8.50 -4.50
c   NaN   NaN
d  9.25 -5.81
            one       two
count  3.000000  2.000000
mean   3.083333 -2.905000
std    3.493685  2.255671
min    0.750000 -4.500000
25%    1.075000 -3.702500
50%    1.400000 -2.905000
75%    4.250000 -2.107500
max    7.100000 -1.310000

count     16
unique     4
top        a
freq       4
dtype: object

In [178]:
# Getting unique values in a series
print(obj.unique())

# Getting value frequencies
print(obj.value_counts())

# Checking set membership, which is useful in filtering a dataset
print(obj.isin(['b', 'c']))
print(obj[obj.isin(['b', 'c'])])

['a' 'b' 'c' 'd']
a    4
b    4
c    4
d    4
Name: count, dtype: int64
0     False
1      True
2      True
3     False
4     False
5      True
6      True
7     False
8     False
9      True
10     True
11    False
12    False
13     True
14     True
15    False
dtype: bool
1     b
2     c
5     b
6     c
9     b
10    c
13    b
14    c
dtype: object